// app/faq/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { motion, AnimatePresence } from 'framer-motion'

export default function FAQPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [openItems, setOpenItems] = useState<number[]>([])
  const [willModalOpen, setWillModalOpen] = useState(false)

  const toggleMenu = () => setMobileMenuOpen(!mobileMenuOpen)

  const toggleFAQ = (index: number) => {
    setOpenItems(prev => 
      prev.includes(index) ? prev.filter(i => i !== index) : [...prev, index]
    )
  }

  const expandAll = () => {
    setOpenItems(faqs.map((_, i) => i))
  }

  const collapseAll = () => {
    setOpenItems([])
  }

  const playVideo = (which: string, src: string) => {
    const wrap = document.getElementById('wrap-' + which)
    if (!wrap) return
    wrap.innerHTML = '<iframe width="100%" height="100%" src="' + src + '" frameBorder="0" allow="autoplay; encrypted-media" allowFullScreen style="position:absolute;top:0;left:0;width:100%;height:100%;border-radius:12px"></iframe>'
  }

  const faqs = [
    { q: 'Is this realistic?', a: 'Yes — because it\'s funded by math, not hope. Telehealth pays for itself within months. The entire solution becomes 100% self‑sustaining in under a year because the savings generated by TeleCARE exceed the cost of everything PHIERS provides. This isn\'t a wishlist. It\'s a financially grounded systems upgrade.' },
    { q: 'Why telehealth first?', a: 'Because it\'s the first domino — and the one that pays for the rest. Telehealth is already: cheaper, faster, nationwide, scalable, and proven. And the savings from TeleCARE cover the cost of every other PHIERS benefit after the first year of operation.' },
    { q: 'Why 3.5%?', a: 'Because 3.5% is the tipping point. Roughly 12 million people — about 3.5% of the U.S. population — is enough to compel Congress to show up to town halls where constituents can clearly state what must be done to avoid being primaried before 2026. 3.5% gives them the incentive. PHIERS gives the people the leverage.' },
    { q: 'Why not wait for Congress to act on its own?', a: 'Because they won\'t. Congress has the authority, the money, and the infrastructure — but not the incentive. 3.5% gives them the incentive. PHIERS gives teeth to the demands of "We the People."' },
    { q: 'Is this partisan?', a: 'No. Healthcare, stability, jobs, and democracy are not partisan issues — they\'re human issues. This movement includes conservatives, liberals, independents, libertarians, apolitical Americans, and people who\'ve never voted. The only requirement is wanting a country that works.' },
    { q: 'Is this socialism?', a: 'No. PHIERS is a public‑benefit corporation and a grassroots cooperative marketplace and insurance plan — 100% owned, operated, and accountable to its members (We the People). Nothing is nationalized. Nothing is government‑run. Nothing is controlled by donors or corporations that profit from keeping people sick, poor, or divided. This is market‑efficient, cost‑reducing, and freedom‑expanding.' },
    { q: 'How does this get funded?', a: 'By saving money — not spending more. TeleCARE offered through the ACA exchange becomes a lower‑cost option for CMS, allowing them to save money directly attributable to awarding contracts to the people\'s platform. No new taxes. No new bureaucracy. Just redirecting waste into solutions that work.' },
    { q: 'How does this create jobs?', a: 'By creating a stable, inclusive, community‑powered economy. As a cooperative and bartering platform, PHIERS supports work from: health and social workers, mental health professionals, medical transportation providers, addiction, trauma, and depression counselors, child and adult day‑care providers, tradespeople, community gardeners, cooks, cleaners, builders — anyone providing value to their community. This creates self‑sustaining, meaningful jobs that improve life for everyone.' },
    { q: 'How does this protect democracy?', a: 'By restoring accountability. When we reach 1,500 signatures on the petition, representatives are compelled to attend town halls where constituents present clear, district‑specific demands. This is how we force Congress to: End the wars, Prevent the draft, Authorize TeleCARE through the ACA, Unlock trillions in annual savings, Put constituent interests ahead of the donors. If they refuse, we recall, replace, or primary every candidate who ignores their constituents. This is how democracy protects itself.' },
    { q: 'What happens after I sign?', a: 'Three things: (1) Your signature counts toward your district\'s 1,500 petition signature threshold. (2) Your representative becomes accountable to your district\'s demands. (3) You\'re invited to town hall meetings and ongoing surveys to keep your voice front and center. Once petition, marketplace and benefit thresholds are reached, you\'ll be notified and invited to participate as each component comes online.' },
    { q: 'What if Congress still refuses?', a: 'Then we replace them — peacefully, legally, and at scale. This movement is built for: Primaries, General elections, District‑level mobilization, Accountability. No violence. No chaos. Just organized civic power.' },
    { q: 'Why now?', a: 'Because waiting makes everything worse. The crisis is unfolding now. The system is failing now. People are suffering now. Jobs are disappearing now. Authoritarian risk is rising now. And because the math finally works. This is the first time in decades that a peaceful, scalable, intelligent solution has been possible — and delaying means losing access to fuel, fertilizer, and stability as global conditions worsen. PHIERS is inviting the public to prepare together, plan together, and build a better future while we still can.' },
  ]

  return (
    <>
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#080d1a]/95 backdrop-blur-md border-b border-[#3ddc84]/20 px-6 h-16 flex items-center justify-between">
        <Link href="/" className="font-condensed font-bold text-xl text-white tracking-wide">PHIERS.org</Link>
        <div className="flex items-center gap-4">
          <Link href="/petition" className="hidden md:inline-block px-5 py-2 bg-red-600 text-white font-condensed font-bold text-sm rounded-lg hover:bg-red-700 transition-all">✍ Sign the Petition</Link>
          <button onClick={toggleMenu} className="md:hidden text-white text-2xl p-2 border border-white/20 rounded-lg">{mobileMenuOpen ? '✕' : '☰'}</button>
        </div>
      </nav>

      {/* Mobile Menu */}
      <AnimatePresence>
        {mobileMenuOpen && (
          <motion.div className="fixed top-16 left-0 right-0 bg-[#0d1525] border-b border-[#3ddc84]/20 z-40 p-5 max-h-[calc(100vh-64px)] overflow-y-auto" initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }}>
            <div className="space-y-4">
              <Link href="/no-war" className="block p-4 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 font-condensed font-bold text-center" onClick={() => setMobileMenuOpen(false)}>🕊 END THE WAR / NO DRAFT</Link>
              <details className="border-b border-white/10 pb-2"><summary className="font-condensed font-bold text-white py-2 cursor-pointer list-none">Understand the Fight</summary>
                <div className="space-y-2 pl-4 mt-2"><Link href="/crisis" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>🚨 The Crisis</Link><Link href="/simple-math" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>📊 Simple Math</Link><Link href="/how-it-works" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>⚡ The Leverage</Link><Link href="/solutions" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>🔬 5D Solutions</Link><Link href="/telecare" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>💡 TeleCARE</Link></div>
              </details>
              <details className="border-b border-white/10 pb-2"><summary className="font-condensed font-bold text-white py-2 cursor-pointer list-none">Who We're For</summary>
                <div className="space-y-2 pl-4 mt-2"><Link href="/organizers" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>✊ For Organizers</Link><Link href="/veterans" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>🎖 Veterans</Link><Link href="/unions" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>💪 Union Strategy</Link></div>
              </details>
              <details className="border-b border-white/10 pb-2"><summary className="font-condensed font-bold text-white py-2 cursor-pointer list-none">Resources</summary>
                <div className="space-y-2 pl-4 mt-2"><Link href="/resources" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>📚 Resource Hub</Link><Link href="/real-stories" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>💬 Real Stories</Link><Link href="/faq" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>❓ FAQ</Link><Link href="/about" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>📖 About</Link></div>
              </details>
              <details className="border-b border-white/10 pb-2"><summary className="font-condensed font-bold text-white py-2 cursor-pointer list-none">Take Action</summary>
                <div className="space-y-2 pl-4 mt-2"><Link href="/petition" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>📋 Sign the Petition</Link><Link href="/donate" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>💚 Donate</Link><Link href="/action" className="block text-gray-400 py-1" onClick={() => setMobileMenuOpen(false)}>📣 Take Action</Link></div>
              </details>
              <Link href="/petition" className="block w-full py-3 bg-[#3ddc84] text-[#080d1a] font-condensed font-bold text-center rounded-lg mt-4" onClick={() => setMobileMenuOpen(false)}>✍ Sign Now</Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <main className="pt-20 pb-16 max-w-[1000px] mx-auto px-6">
        {/* Back Link */}
        <Link href="/" className="inline-block font-condensed text-[#3ddc84] text-sm border border-[#3ddc84]/30 rounded-full px-4 py-2 mb-6 hover:bg-[#3ddc84]/10 transition-all">← Back to PHIERS.org</Link>

        {/* Hero Section */}
        <div className="text-center bg-gradient-to-br from-[#0f3460]/90 to-[#16213e]/90 rounded-xl border border-[#3ddc84]/20 p-8 md:p-12 mb-12 relative overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-transparent via-[#3ddc84] to-transparent"></div>
          <div className="flex justify-center mb-6"><Image src="/images/PHIERS_Logo.png" alt="PHIERS.org" width={100} height={100} className="opacity-90" /></div>
          <div className="font-condensed text-gray-500 text-xs tracking-wide mb-2">❓ QUESTIONS & ANSWERS</div>
          <h1 className="font-display text-4xl md:text-5xl text-white mt-2 mb-2">FREQUENTLY ASKED<br /><span className="text-[#ffd60a]">QUESTIONS</span></h1>
          <p className="text-gray-400 text-lg max-w-[700px] mx-auto">Honest answers. Clear explanations. No political jargon.</p>
        </div>

        {/* Video Section */}
        <div className="bg-gradient-to-br from-blue-500/10 to-blue-500/5 border-2 border-blue-500/30 rounded-xl p-6 md:p-8 my-8">
          <h2 className="font-display text-2xl md:text-3xl text-blue-400 text-center mb-6">THE MATH BEHIND THE ANSWERS</h2>
          <div className="relative aspect-video rounded-xl overflow-hidden border border-blue-500/30">
            <div id="wrap-faq-math" className="relative w-full h-full">
              <div className="absolute inset-0 bg-cover bg-center cursor-pointer flex items-center justify-center" style={{ backgroundImage: "url('https://img.youtube.com/vi/2j-dF3hgdeE/hqdefault.jpg')" }} onClick={() => playVideo('faq-math', 'https://www.youtube.com/embed/2j-dF3hgdeE?autoplay=1&rel=0')}>
                <div className="absolute inset-0 bg-black/30 flex items-center justify-center text-5xl text-white/90 cursor-pointer">▶</div>
              </div>
            </div>
          </div>
          <p className="text-center text-blue-400 font-bold mt-4">1 minute 11 seconds. This is why they're terrified.</p>
        </div>

        {/* Intro Statement */}
        <div className="text-center my-8">
          <p className="font-condensed text-xl text-white max-w-[800px] mx-auto">People deserve straight answers — not spin, not talking points, not bureaucratic fog. This movement is built on clarity, transparency, and math.</p>
        </div>

        {/* Expand/Collapse Controls */}
        <div className="flex justify-center gap-3 my-6">
          <button onClick={expandAll} className="px-5 py-2 bg-transparent border border-[#3ddc84]/30 rounded-full text-gray-400 text-sm font-condensed hover:border-[#3ddc84] hover:text-[#3ddc84] transition-all">+ EXPAND ALL</button>
          <button onClick={collapseAll} className="px-5 py-2 bg-transparent border border-[#3ddc84]/30 rounded-full text-gray-400 text-sm font-condensed hover:border-[#3ddc84] hover:text-[#3ddc84] transition-all">− COLLAPSE ALL</button>
        </div>

        {/* FAQ Grid */}
        <div className="space-y-4 my-8">
          {faqs.map((faq, index) => (
            <div key={index} className={`bg-[#111d35] border-2 rounded-xl overflow-hidden transition-all ${openItems.includes(index) ? 'border-[#3ddc84]' : 'border-[#3ddc84]/20'}`}>
              <button onClick={() => toggleFAQ(index)} className="w-full p-5 flex justify-between items-center text-left hover:bg-[#3ddc84]/5 transition-colors">
                <h2 className="font-condensed text-xl md:text-2xl text-[#ffd60a] m-0">{index + 1}. {faq.q}</h2>
                <span className={`font-condensed text-2xl text-[#3ddc84] w-10 h-10 flex items-center justify-center rounded-full bg-[#3ddc84]/10 transition-all ${openItems.includes(index) ? 'rotate-45' : ''}`}>{openItems.includes(index) ? '×' : '+'}</span>
              </button>
              <div className={`overflow-hidden transition-all duration-500 ${openItems.includes(index) ? 'max-h-[1000px]' : 'max-h-0'}`}>
                <div className="p-5 pt-0 bg-black/20 border-t border-[#3ddc84]/20">
                  <p className="text-gray-300 leading-relaxed">{faq.a}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Math Note */}
        <div className="bg-[#3ddc84]/10 border border-[#3ddc84]/30 rounded-xl p-8 text-center my-10">
          <p className="text-2xl md:text-3xl font-display text-white mb-2">3.5% organized = <span className="text-[#ffd60a] text-3xl md:text-4xl">unstoppable change</span></p>
          <p className="text-xl md:text-2xl text-white mb-4">12 million Americans. <span className="text-[#ffd60a] text-2xl md:text-3xl">That's the line.</span></p>
          <p className="text-lg text-white mt-4">Energy without power fails. PHIERStorm is the power.</p>
          <p className="text-[#3ddc84] font-display text-xl tracking-wide mt-4 pt-4 border-t border-[#3ddc84]/20">PHIERS.org is a Catalyst for Positive Change</p>
        </div>

        {/* Final CTA */}
        <div className="bg-gradient-to-br from-[#3ddc84]/10 to-[#ffd60a]/10 border-2 border-[#ffd60a] rounded-xl p-8 md:p-12 text-center my-12">
          <h2 className="font-display text-3xl md:text-4xl text-[#3ddc84] mb-3">QUESTIONS ANSWERED.<br /><span className="text-[#ffd60a]">NOW ACT.</span></h2>
          <p className="text-gray-300 text-lg mb-6">You've seen the answers. You've seen the math. You've seen the mechanism.<br />Now help ignite the cascade.</p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link href="/petition" className="px-8 py-4 bg-red-600 text-white font-condensed font-bold rounded-lg hover:bg-red-700 transition-all">✍ Sign the Petition</Link>
            <Link href="/action" className="px-8 py-4 bg-transparent text-[#3ddc84] border border-[#3ddc84] rounded-lg font-condensed font-bold hover:bg-[#3ddc84]/10 transition-all">🌊 JOIN THE STORM</Link>
          </div>
          <p className="font-condensed text-gray-500 mt-6">3.5% organized = unstoppable change. 12 million Americans. That's the line.</p>
        </div>
      </main>

      {/* FOOTER */}
      <footer className="text-center py-12 px-6 border-t border-[#3ddc84]/10 bg-[#0d1525]">
        <Image src="/images/PHIERS_Logo.png" alt="PHIERS.org" width={80} height={80} className="mx-auto mb-4 opacity-70" />
        <div className="font-condensed font-bold text-gray-400 mb-1">PHIERS is a people's movement — not a company, not a product.</div>
        <div className="text-sm text-gray-500 mb-4">Built by regular people who are done waiting.</div>
        <div className="max-w-[500px] mx-auto mb-6">
          <p className="font-condensed text-gray-400">Energy without power fails.<br />PHIERStorm is the power.<br /><span className="text-gray-500">PHIERS.org — a catalyst for the change we've been waiting for.</span><br /><span className="text-gray-500">The only thing missing is you.</span></p>
        </div>
        <div className="max-w-[560px] mx-auto p-5 border border-[#3ddc84]/15 rounded-lg mb-6">
          <p className="font-condensed text-gray-500 text-xs uppercase tracking-wide mb-2">Built by</p>
          <p className="font-condensed font-bold text-white">Will Price | Founder &amp; Chief Solutions Architect</p>
          <p className="font-condensed text-gray-400 text-sm mb-3">Not a politician. Not a lobbyist. A systems architect who found $2.7 trillion in wasted spending and built the lever to fix it. Building this since 2009.</p>
          <button onClick={() => setWillModalOpen(true)} className="font-condensed text-[#3ddc84] text-sm border-b border-[#3ddc84]/30">👤 Meet the Architect →</button>
        </div>
        <div className="flex flex-wrap justify-center gap-4 max-w-2xl mx-auto mb-6">
          <Link href="/crisis" className="text-gray-500 text-sm hover:text-[#3ddc84]">The Crisis</Link>
          <Link href="/simple-math" className="text-gray-500 text-sm hover:text-[#3ddc84]">Simple Math</Link>
          <Link href="/solutions" className="text-gray-500 text-sm hover:text-[#3ddc84]">5D Solutions</Link>
          <Link href="/telecare" className="text-gray-500 text-sm hover:text-[#3ddc84]">Telehealth</Link>
          <Link href="/no-war" className="text-gray-500 text-sm hover:text-[#3ddc84]">No War / No Draft</Link>
          <Link href="/organizers" className="text-gray-500 text-sm hover:text-[#3ddc84]">Organizers</Link>
          <Link href="/unions" className="text-gray-500 text-sm hover:text-[#3ddc84]">Unions</Link>
          <Link href="/donate" className="text-gray-500 text-sm hover:text-[#3ddc84]">Donate</Link>
          <Link href="/faq" className="text-gray-500 text-sm hover:text-[#3ddc84]">FAQ</Link>
          <Link href="/about" className="text-gray-500 text-sm hover:text-[#3ddc84]">About</Link>
        </div>
        <div className="text-xs text-gray-600">
          Not built for profit. Not built for power. Built for We the People — by people who refused to stop.<br />
          📧 <a href="mailto:info@phiers.org" className="text-[#3ddc84]">info@phiers.org</a> · 📞 (916) 306-8967<br />
          © PHIERS.org — Original Concept Since 2009. All Rights Reserved.<br />
          <span className="text-[0.7rem]">PHIERS™ · PHIERSale™ · PHIERWorks™ · PHIERPlace™ — Protected marks established 2009–2025.</span>
        </div>
      </footer>

      <button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="fixed bottom-6 right-6 bg-[#3ddc84] text-[#080d1a] w-11 h-11 rounded-full flex items-center justify-center text-xl hover:bg-[#2ab568] transition-all shadow-lg z-40">↑</button>

      {/* Will Price Modal */}
      <AnimatePresence>
        {willModalOpen && (
          <motion.div className="fixed inset-0 bg-black/90 z-[99998] flex items-center justify-center p-4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setWillModalOpen(false)}>
            <div className="relative max-w-[720px] w-full bg-[#080d1a]/97 border-2 border-[#3ddc84]/35 rounded-2xl shadow-2xl overflow-y-auto max-h-[90vh]" onClick={(e) => e.stopPropagation()}>
              <button onClick={() => setWillModalOpen(false)} className="absolute top-3 right-3 w-10 h-10 rounded-full bg-[#111d35] text-[#3ddc84] border-2 border-[#3ddc84] flex items-center justify-center text-xl hover:bg-[#3ddc84] hover:text-[#111d35] transition-all z-10">✕</button>
              <div className="flex flex-wrap">
                <div className="w-full md:w-[240px] min-h-[280px] overflow-hidden"><img src="/images/Will_Price.png" alt="Will Price" className="w-full h-full min-h-[260px] object-cover object-[55%_top]" /></div>
                <div className="flex-1 min-w-[240px] p-7 flex flex-col justify-center">
                  <p className="font-condensed text-xs text-[#3ddc84] uppercase tracking-[3px] mb-2">The Architect</p>
                  <h3 className="font-display text-2xl md:text-3xl text-white leading-tight mb-1">Will Price</h3>
                  <p className="font-condensed text-sm text-[#ffd60a] font-bold mb-4">Founder &amp; Chief Solutions Architect, PHIERS</p>
                  <p className="font-body text-sm text-[#c8d8c8] leading-relaxed">Not a politician. Not a lobbyist. A systems architect who found $2.7 trillion in wasted spending — and built the lever to redirect it toward healthcare, jobs, and a monthly check for every American. Building this since 2009.</p>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <style jsx global>{`
        .font-display { font-family: 'Bebas Neue', sans-serif; }
        .font-condensed { font-family: 'Barlow Condensed', sans-serif; }
        .font-body { font-family: 'Barlow', sans-serif; }
        details summary { list-style: none; }
        details summary::-webkit-details-marker { display: none; }
      `}</style>
    </>
  )
}
