// FILE: app/faq/page.tsx - UPDATED (Tiers 1-7)

'use client'

import { useState, useCallback } from 'react'  // ✓ Added useCallback
import Image from 'next/image'
import Link from 'next/link'
import { motion, AnimatePresence } from 'framer-motion'
import Navigation from '@/components/navigation'
import Footer from '@/components/footer'
import Button from '@/components/Button'

export default function FAQPage() {
  const [openItems, setOpenItems] = useState<number[]>([])
  const [modalImage, setModalImage] = useState<string | null>(null)

  // ✓ Added scrollToTop function
  const scrollToTop = useCallback(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [])

  const openModal = (src: string) => {
    setModalImage(src)
    document.body.style.overflow = 'hidden'
  }

  const closeModal = () => {
    setModalImage(null)
    document.body.style.overflow = ''
  }

  // ✓ Wrapped toggleFAQ in useCallback
  const toggleFAQ = useCallback((index: number) => {
    if (openItems.includes(index)) {
      setOpenItems(openItems.filter(i => i !== index))
    } else {
      setOpenItems([...openItems, index])
    }
  }, [openItems])

  // ✓ Wrapped expandAll in useCallback
  const expandAll = useCallback(() => {
    setOpenItems([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
  }, [])

  // ✓ Wrapped collapseAll in useCallback
  const collapseAll = useCallback(() => {
    setOpenItems([])
  }, [])

  // ✓ Wrapped playVideo in useCallback
  const playVideo = useCallback((videoId: string, src: string) => {
    const wrap = document.getElementById('wrap-' + videoId)
    if (!wrap) return
    wrap.innerHTML = '<iframe width="100%" height="100%" src="' + src +
      '" frameBorder="0" allow="autoplay; encrypted-media" allowFullScreen ' +
      'style="position:absolute;top:0;left:0;width:100%;height:100%;border-radius:12px"></iframe>'
  }, [])

  const faqs = [
    {
      q: "1. Is this realistic?",
      a: "<strong style='color:var(--gold);'>Yes — because it's funded by math, not hope.</strong><br><br>Telehealth pays for itself within months.<br><br>The entire solution becomes 100% self‑sustaining in under a year because the savings generated by TeleCARE exceed the cost of everything PHIERS provides.<br><br><span style='color:var(--green);font-weight:700;'>This isn't a wishlist. It's a financially grounded systems upgrade.</span>"
    },
    {
      q: "2. Why telehealth first?",
      a: "<strong style='color:var(--gold);'>Because it's the first domino — and the one that pays for the rest.</strong><br><br>Telehealth is already:<br>• Cheaper<br>• Faster<br>• Nationwide<br>• Scalable<br>• Proven<br><br>And the savings from TeleCARE cover the cost of every other PHIERS benefit after the first year of operation."
    },
    {
      q: "3. Why 3.5%?",
      a: "<strong style='color:var(--gold);'>Because 3.5% is the tipping point.</strong><br><br>Roughly 12 million people — about 3.5% of the U.S. population — is enough to compel Congress to show up to town halls where constituents can clearly state what must be done to avoid being primaried before November 2026.<br><br>3.5% gives them the incentive.<br>PHIERS gives the people the leverage."
    },
    {
      q: "4. Why not wait for Congress?",
      a: "<strong style='color:var(--gold);'>Because they won't.</strong><br><br>Congress has the authority, the money, and the infrastructure — but not the incentive.<br><br>3.5% gives them the incentive.<br>PHIERS gives teeth to the demands of 'We the People.'"
    },
    {
      q: "5. Is this partisan?",
      a: "<strong style='color:var(--gold);'>No.</strong><br><br>Healthcare, stability, jobs, and democracy are not partisan issues — they're human issues.<br><br>This movement includes conservatives, liberals, independents, libertarians, apolitical Americans, and people who've never voted.<br><br><span style='color:var(--green);font-weight:700;'>The only requirement is wanting a country that works.</span>"
    },
    {
      q: "6. Is this socialism?",
      a: "<strong style='color:var(--gold);'>No.</strong><br><br>PHIERS is a public‑benefit corporation and a grassroots cooperative marketplace and insurance plan — 100% owned, operated, and accountable to its members (We the People).<br><br>Nothing is nationalized.<br>Nothing is government‑run.<br>Nothing is controlled by donors or corporations that profit from keeping people sick, poor, or divided.<br><br>This is market‑efficient, cost‑reducing, and freedom‑expanding."
    },
    {
      q: "7. How does this get funded?",
      a: "<strong style='color:var(--gold);'>By saving money — not spending more.</strong><br><br>TeleCARE offered through the ACA exchange becomes a lower‑cost option for CMS, allowing them to save money directly attributable to awarding contracts to the people's platform.<br><br>PHIERS can also receive performance‑based grants because it undercuts every competitor while improving outcomes.<br><br>No new taxes.<br>No new bureaucracy.<br>Just redirecting waste into solutions that work."
    },
    {
      q: "8. How does this create jobs?",
      a: "<strong style='color:var(--gold);'>By creating a stable, inclusive, community‑powered economy.</strong><br><br>As a cooperative and bartering platform, PHIERS supports work from:<br>• Health and social workers<br>• Mental health professionals<br>• Medical transportation providers<br>• Addiction, trauma, and depression counselors<br>• Child and adult day‑care providers<br>• Tradespeople for repairs and maintenance<br>• Community gardeners, cooks, cleaners, and builders<br>• Anyone providing value to their community<br><br>Instead of paying only in dollars, PHIERS provides benefits through the PHIERsale marketplace and the PHIERplace resource‑matching network.<br><br>This creates self‑sustaining, meaningful jobs that improve life for everyone — both the beneficiary and the provider."
    },
    {
      q: "9. How does this protect democracy?",
      a: "<strong style='color:var(--gold);'>By restoring accountability.</strong><br><br>When we reach 1,500 signatures on the petition, representatives are compelled to attend town halls where constituents present clear, district‑specific demands.<br><br>This is how we force Congress to:<br>• End the wars<br>• Prevent the draft<br>• Authorize TeleCARE through the ACA<br>• Unlock trillions in annual savings<br>• Put constituent interests ahead of the donors<br><br>If they refuse, we recall, replace, or primary every candidate who ignores their constituents.<br><br><span style='color:var(--green);font-weight:700;'>This is how democracy protects itself.</span>"
    },
    {
      q: "10. What happens after I sign?",
      a: "<strong style='color:var(--gold);'>Three things:</strong><br><br>1. Your signature counts toward your district's 1,500 petition signature threshold.<br>2. Your representative becomes accountable to your district's demands.<br>3. You're invited to town hall meetings and ongoing surveys to keep your voice front and center.<br><br>Once petition, marketplace and benefit thresholds are reached, you'll be notified and invited to participate as each component comes online.<br><br>We expect major milestones before the end of the year — because that's when we plan to reclaim our independence from authoritarian drift and a do‑nothing Congress."
    },
    {
      q: "11. What if Congress still refuses?",
      a: "<strong style='color:var(--gold);'>Then we replace them — peacefully, legally, and at scale.</strong><br><br>This movement is built for:<br>• Primaries<br>• General elections<br>• District‑level mobilization<br>• Accountability<br><br>No violence.<br>No chaos.<br>Just organized civic power."
    },
    {
      q: "12. Why now?",
      a: "<strong style='color:var(--gold);'>Because waiting makes everything worse.</strong><br><br>• The crisis is unfolding now<br>• The system is failing now<br>• People are suffering now<br>• Jobs are disappearing now<br>• Authoritarian risk is rising now<br><br><strong>And because the math finally works.</strong><br><br>This is the first time in decades that a peaceful, scalable, intelligent solution has been possible — and delaying means losing access to fuel, fertilizer, and stability as global conditions worsen.<br><br><span style='color:var(--green);font-weight:700;'>PHIERS is inviting the public to prepare together, plan together, and build a better future while we still can. The window is open right now.</span>"
    }
  ]

  return (
    <>
      <Navigation />

      <main>
        {/* Hero */}
        <div className="container section text-center pt-32">
          <div className="relative h-[100px] w-auto mb-6 flex justify-center">
            <Image
              src="/images/PHIERS_Logo.png"
              alt="PHIERS.org"
              width={100}
              height={100}
              className="opacity-90"
            />
          </div>
          <div className="font-condensed font-bold text-green text-sm uppercase tracking-wider block mb-3">❓ QUESTIONS & ANSWERS</div>
          {/* ✓ Fixed two-tone H1 */}
          <h1 className="mb-4">
            <span className="hero-white">FREQUENTLY ASKED</span>
            <br />
            <span className="hero-green">QUESTIONS</span>
          </h1>
          <p className="font-condensed text-lg text-gray-400 max-w-[750px] mx-auto">
            Honest answers. Clear explanations. No political jargon.
          </p>
        </div>

        {/* ✓ Anchor line added after Hero section */}
        <div className="container py-8 my-4 border-t-2 border-b-2 border-green/30 text-center">
          <p className="font-display text-xl md:text-2xl text-white font-extrabold">
            Nothing changes until ignoring people costs more than responding to them.<br />
            <span className="text-green">PHIERS is how we raise that cost.</span>
          </p>
        </div>

        {/* Video Section */}
        <section className="container section">
          <div className="bg-bg-card border-2 border-green/20 rounded-xl p-6 max-w-[800px] mx-auto">
            <h2 className="font-display text-2xl text-gold text-center mb-4">THE MATH BEHIND THE ANSWERS</h2>
            <div className="video-container max-w-[560px] mx-auto">
              <div id="wrap-faq-math" className="video-wrapper cursor-pointer group" onClick={() => playVideo('faq-math', 'https://www.youtube.com/embed/2j-dF3hgdeE?autoplay=1&rel=0')}>
                <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: "url('https://img.youtube.com/vi/2j-dF3hgdeE/hqdefault.jpg')" }}>
                  <div className="absolute inset-0 bg-black/40 flex items-center justify-center group-hover:bg-black/30 transition-all">
                    <div className="w-12 h-12 rounded-full bg-red-600 flex items-center justify-center text-white text-xl">▶</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-3 text-center">
              <div className="font-display text-sm text-green">🎥 The Math Congress Fears — PHIERS Explainer</div>
              <div className="font-condensed text-xs text-gray-500">1 minute 11 seconds. This is why they're terrified.</div>
            </div>
          </div>
        </section>

        {/* Intro Statement */}
        <div className="text-center my-8 px-4">
          <p className="font-condensed text-lg text-white max-w-[800px] mx-auto">
            People deserve straight answers — not spin, not talking points, not bureaucratic fog.
            This movement is built on clarity, transparency, and math.
          </p>
        </div>

        {/* Expand/Collapse Controls */}
        <div className="flex justify-center gap-3 my-6">
          <button onClick={expandAll} className="px-5 py-2 border border-green/20 rounded-full text-gray-400 text-sm font-condensed font-bold hover:border-green hover:text-green transition-all">+ EXPAND ALL</button>
          <button onClick={collapseAll} className="px-5 py-2 border border-green/20 rounded-full text-gray-400 text-sm font-condensed font-bold hover:border-green hover:text-green transition-all">− COLLAPSE ALL</button>
        </div>

        {/* FAQ Grid */}
        <div className="max-w-[900px] mx-auto px-4 space-y-3 mb-12">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-bg-card border-2 border-green/20 rounded-xl overflow-hidden hover:border-green transition-all">
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full p-5 flex justify-between items-center text-left hover:bg-green/5 transition-all"
              >
                <h2 className="font-condensed text-xl md:text-2xl text-gold">{faq.q}</h2>
                <span className="font-condensed text-2xl text-green w-10 h-10 flex items-center justify-center rounded-full bg-green/10 transition-all">
                  {openItems.includes(index) ? '×' : '+'}
                </span>
              </button>
              <div
                className={`overflow-hidden transition-all duration-500 ${
                  openItems.includes(index) ? 'max-h-[1000px] opacity-100' : 'max-h-0 opacity-0'
                }`}
              >
                <div className="p-5 pt-0 border-t border-green/20 bg-black/20">
                  <div className="text-body" dangerouslySetInnerHTML={{ __html: faq.a }} />
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Math Note */}
        <div className="bg-green-glow border border-green rounded-xl p-8 max-w-[800px] mx-auto my-12 text-center">
          <p className="font-display text-3xl text-white mb-3">3.5% organized = <span className="text-gold">unstoppable change</span></p>
          <p className="font-display text-2xl text-white mb-4">12 million Americans. <span className="text-gold">That's the line.</span></p>
          <p className="font-condensed text-xl text-white mb-3">Energy without power fails. PHIERStorm is the power.</p>
          <div className="border-t border-green/20 pt-4 mt-3">
            <p className="font-display text-xl text-green">PHIERS.org is a Catalyst for Positive Change</p>
          </div>
        </div>

        {/* Final CTA */}
        <div className="bg-gold-glow border-2 border-gold rounded-xl p-8 max-w-[700px] mx-auto my-12 text-center">
          <h3 className="font-display text-3xl text-white mb-3">QUESTIONS ANSWERED.<br /><span className="text-gold">NOW ACT.</span></h3>
          <p className="text-body mb-6">You've seen the answers. You've seen the math. You've seen the mechanism.<br />Now help ignite the cascade.</p>
          <div className="flex flex-col md:flex-row gap-3 justify-center">
            <Button href="/petition" variant="primary">✍ SIGN THE PETITION</Button>
            <Button href="/action" variant="secondary">🌊 JOIN THE MOVEMENT</Button>
          </div>
          <p className="font-condensed text-gray-500 text-sm mt-4">3.5% organized = unstoppable change. 12 million Americans. That's the line.</p>
        </div>
      </main>

      <Footer />

      {/* Image Modal */}
      <AnimatePresence>
        {modalImage && (
          <motion.div
            className="fixed inset-0 bg-black/95 z-[99999] flex items-center justify-center p-4"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={closeModal}
          >
            <div className="relative max-w-[90vw] max-h-[90vh]" onClick={(e) => e.stopPropagation()}>
              <button
                onClick={closeModal}
                className="absolute -top-10 right-0 text-white text-3xl cursor-pointer hover:text-green transition-colors"
              >
                ✕
              </button>
              <Image
                src={modalImage}
                alt="Enlarged view"
                width={800}
                height={600}
                className="rounded-xl"
              />
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ✓ Updated back-to-top button to use scrollToTop */}
      <button 
        onClick={scrollToTop}
        className="back-to-top"
        id="back-to-top"
        aria-label="Back to top"
      >
        ↑
      </button>

      <style jsx global>{`
        .back-to-top {
          position: fixed;
          bottom: 24px;
          right: 24px;
          background: var(--green);
          color: var(--bg-deep);
          width: 48px;
          height: 48px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 24px;
          cursor: pointer;
          opacity: 0;
          visibility: hidden;
          transition: all 150ms ease;
          z-index: 999;
          border: none;
        }
        .back-to-top.visible {
          opacity: 1;
          visibility: visible;
        }
        .back-to-top:hover {
          background: #2ab568;
          transform: translateY(-2px);
        }
        .bg-green-glow {
          background: rgba(61, 220, 132, 0.06);
        }
        .bg-gold-glow {
          background: rgba(245, 200, 66, 0.08);
        }
        .video-container {
          position: relative;
          padding-bottom: 56.25%;
          height: 0;
          overflow: hidden;
          border-radius: 12px;
          border: 2px solid rgba(61, 220, 132, 0.2);
          box-shadow: 0 12px 40px rgba(0, 0, 0, 0.5);
        }
        .video-wrapper {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          cursor: pointer;
        }
      `}</style>

      <script dangerouslySetInnerHTML={{
        __html: `
          window.addEventListener('scroll', function() {
            var btt = document.getElementById('back-to-top');
            if (btt) {
              if (window.scrollY > 400) {
                btt.classList.add('visible');
              } else {
                btt.classList.remove('visible');
              }
            }
          });
        `
      }} />
    </>
  )
}

// END FILE: app/faq/page.tsx - TIERS 1-7 COMPLETE
